version: '3.9'

services:
  app:
    image: node:24.10.0
    container_name: shooting-session-app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - ./:/usr/src/app:delegated
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - '3001:3000'
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: shooting-session-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer:4
    container_name: shooting-session-adminer
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # For reference only; Adminer connects via UI.
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"
volumes:
  pgdata:
