version: '3.9'

services:
  app:
    image: node:24.10.0
    container_name: shooting-session-app
    working_dir: /usr/src/app
    command: sh -c "npm run dev:install"
    volumes:
      - ./:/usr/src/app:delegated
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - '3001:3000'
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: shooting-session-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
